dist: bionic
os: linux
language: php

before_script:
  - phpenv config-rm xdebug.ini || true

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  include:
    - php: 7.4
    - php: 7.2
      # if: branch = master AND fork = false
      env:
        - UPDATE_RESOURCES=true
        - secure: "KdRIoeVMAjv63erXmG3EkOnE/UrIsgIJ7/S3yZwJq3y+c6jd7Xax6lNWRF6PcfKtNHJNhreIKA/skW5CkPktKIKqOrHrJVx5GsIQX3OqW1z2LF/qqDr7zxNWWrCCI13t7uy4GkPNU0xMwauk+5GCoyBrsxwjwf3/Lm3SA7xZTrE="

install:
  - composer install

script:
  - ./vendor/bin/phpunit || travis_terminate 1
  - ./vendor/bin/psalm || travis_terminate 1
  - ./vendor/bin/phpstan analyse -l 5 src || travis_terminate 1
  - ./ci/update.sh
